// Initial content loaded into the database the first time the site starts (only if empty).
// No fake donors / bookings are seeded.
const SEED_NOTICES = [
  {
    id: "not_1",
    titleEn: "Devotee Registration for Kartik Brata passes",
    titleOr: "କାର୍ତ୍ତିକ ବ୍ରତ ପାସ ପାଇଁ ଶ୍ରଦ୍ଧାଳୁ ପଞ୍ଜୀକରଣ",
    titleHi: "कार्तिक व्रत पास के लिए श्रद्धालु पंजीकरण",
    contentEn: "Devotees visiting during Kartik Brata (starting in October) are advised to register at the Temple Trust Office for early morning Darshan passes. Queue management measures are being established.",
    contentOr: "କାର୍ତ୍ତିକ ବ୍ରତ ସମୟରେ (ଅକ୍ଟୋବରରୁ ଆରମ୍ଭ) ଆସୁଥିବା ଶ୍ରଦ୍ଧାଳୁମାନଙ୍କୁ ସକାଳୁ ଦର୍ଶନ ପାସ ପାଇଁ ମନ୍ଦିର ଟ୍ରଷ୍ଟ କାର୍ଯ୍ୟାଳୟରେ ପଞ୍ଜୀକରଣ କରିବାକୁ ପରାମର୍ଶ ଦିଆଯାଇଛି।",
    contentHi: "कार्तिक व्रत (अक्टूबर से शुरू) के दौरान आने वाले श्रद्धालुओं को सलाह दी जाती है कि वे सुबह के दर्शन पास के लिए मंदिर ट्रस्ट कार्यालय में पंजीकरण कराएं।",
    category: "urgent",
    isPinned: true,
    publishDate: "2026-07-04",
    expiryDate: "2026-11-30",
    pdfUrl: "#"
  },
  {
    id: "not_2",
    titleEn: "Weekly Annadan Seva inside Anandabazar Complex",
    titleOr: "ସାପ୍ତାହିକ ଅନ୍ନଦାନ ସେବା ଆନନ୍ଦବଜାର ପରିସରରେ",
    titleHi: "साप्ताहिक अन्नदान सेवा आनंदबाजार परिसर में",
    contentEn: "Annadan Seva (Mahaprasad Distribution) is now fully operational every Sunday from 1:00 PM to 3:00 PM in the new Anandabazar complex behind the temple.",
    contentOr: "ପ୍ରତି ରବିବାର ମଧ୍ୟାହ୍ନ ୧:୦୦ ରୁ ୩:୦୦ ପର୍ଯ୍ୟନ୍ତ ମନ୍ଦିର ପଛପାର୍ଶ୍ଵରେ ଥିବା ଆନନ୍ଦବଜାର ପରିସରରେ ଅନ୍ନଦାନ ସେବା (ମହାପ୍ରସାଦ ସେବନ) ସମ୍ପୂର୍ଣ୍ଣ କାର୍ଯ୍ୟକାରୀ ହେବ।",
    contentHi: "अन्नदान सेवा (महाप्रसाद वितरण) अब मंदिर के पीछे नए आनंदबाजार परिसर में हर रविवार दोपहर 1:00 बजे से 3:00 बजे तक पूरी तरह से चालू है।",
    category: "general",
    isPinned: false,
    publishDate: "2026-06-30",
    expiryDate: "2026-12-31",
    pdfUrl: "#"
  },
  {
    id: "not_3",
    titleEn: "Donations for Boundary Wall construction accepted",
    titleOr: "ସୀମା ପ୍ରାଚୀର ନିର୍ମାଣ ପାଇଁ ଦାନ ଗ୍ରହଣ କରାଯାଉଛି",
    titleHi: "सीमा पर्ची निर्माण के लिए दान स्वीकार किए जाते हैं",
    contentEn: "Donations for the construction of the new boundary wall (Meghnad Pacheri) are accepted through UPI, Net Banking, and at the Temple Office counters. Receipt will be provided instantly.",
    contentOr: "ନୂତନ ସୀମା ପ୍ରାଚୀର (ମେଘନାଦ ପାଚେରୀ) ନିର୍ମାଣ ପାଇଁ ଦାନ UPI, ନେଟ୍ ବ୍ୟାଙ୍କିଙ୍ଗ୍ ଏବଂ ମନ୍ଦିର କାର୍ଯ୍ୟାଳୟ କାଉଣ୍ଟର ମାଧ୍ୟମରେ ଗ୍ରହଣ କରାଯାଉଛି। ରସିଦ ତୁରନ୍ତ ପ୍ରଦାନ କରାଯିବ।",
    contentHi: "नया सीमा पर्ची (मेघनाद पचेरी) के निर्माण के लिए दान यूपीआई, नेट बैंकिंग और मंदिर कार्यालय काउंटर के माध्यम से स्वीकार किए जाते हैं। रसीद तुरंत प्रदान की जाएगी।",
    category: "committee",
    isPinned: false,
    publishDate: "2026-06-15",
    expiryDate: "2026-09-30",
    pdfUrl: "#"
  }
];

const SEED_FESTIVALS = [
  {
    id: "fest_1",
    festivalNameEnglish: "Rath Yatra (Chariot Festival)",
    festivalNameOdia: "ଶ୍ରୀ ଗୁଣ୍ଡିଚା ରଥଯାତ୍ରା",
    festivalNameHindi: "श्री गुंडिचा रथ यात्रा",
    date: "2026-06-26",
    startTime: "06:00 AM",
    endTime: "09:00 PM",
    category: "Major Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "The grand chariot procession of Lord Jagannath to Gundicha Temple.",
    fullDescription: "Rath Yatra is the most auspicious annual festival. Lord Jagannath rides the sacred chariot to the Gundicha temple, pulled by thousands of devotees in a mass assembly of faith.",
    ritualSchedule: "06:30 AM Mangala Alati, 08:30 AM Pahandi Bije, 11:30 AM Chera Pahanra, 03:00 PM Chariot Pulling",
    visitorGuidelines: "Expect extremely large crowds. Follow instructions from police and volunteers. Wheelchair assistance is available at VIP block bypass.",
    parkingInformation: "Two-wheeler parking at High School Ground. Heavy vehicles and cars must park at the Block Office Bypass bypass road.",
    contactInformation: "+91 93378 22942 / Temple Office Control",
    imageUrl: "/assets/temple_chariot_sunset.jpg",
    isFeatured: true,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_2",
    festivalNameEnglish: "Deba Snana Purnima",
    festivalNameOdia: "ଦେବ ସ୍ନାନ ପୂର୍ଣ୍ଣିମା",
    festivalNameHindi: "देव स्नान पूर्णिमा",
    date: "2026-06-09",
    startTime: "05:00 AM",
    endTime: "09:30 PM",
    category: "Jagannath Ritual",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "The bathing festival of the deities followed by the famous Hati Besha (Elephant attire).",
    fullDescription: "Snana Purnima is the bathing festival of Lord Jagannath. The Lord is escorted to the Snana Mandapa and bathed with 108 pots of perfumed water. Afterwards, He is dressed in the Ganesha-like Hati Besha.",
    ritualSchedule: "06:00 AM Jalabhishek, 11:00 AM Snana Niti, 04:00 PM Hati Besha, 08:00 PM Pahada",
    visitorGuidelines: "Photography of Snana Niti is prohibited. Keep queue discipline.",
    parkingInformation: "Free parking at Block Office Ground with shuttle rickshaws.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/jagannath_tulasi_closeup.jpg",
    isFeatured: true,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_3",
    festivalNameEnglish: "Makar Sankranti",
    festivalNameOdia: "ମକର ସଂକ୍ରାନ୍ତି",
    festivalNameHindi: "मकर संक्रांति",
    date: "2026-01-14",
    startTime: "05:30 AM",
    endTime: "08:30 PM",
    category: "Major Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: " Transit of Sun into Capricorn celebrated with Makar Chaula bhoga offerings.",
    fullDescription: "Marks the change of solar cycles. Special Makar Chaula (harvest sweet uncooked rice, ghee, banana, and coconut) is offered to Lord Jagannath. Lord Jagannath is dressed in Makar Vesha.",
    ritualSchedule: "06:00 AM Mangala Aarti, 10:00 AM Makar Chaula offering, 06:30 PM Sandhya Aarti",
    visitorGuidelines: "Arrive early to buy Makar Chaula packages. Long queues expected.",
    parkingInformation: "Normal temple parking available.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_4",
    festivalNameEnglish: "Basant Panchami / Saraswati Puja",
    festivalNameOdia: "ବସନ୍ତ ପଞ୍ଚମୀ",
    festivalNameHindi: "बसंत पंचमी / सरस्वती पूजा",
    date: "2026-01-23",
    startTime: "06:00 AM",
    endTime: "08:00 PM",
    category: "Special Puja",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Offering of yellow flowers and launching the chariot wood collection rituals.",
    fullDescription: "Saraswati Puja marks the onset of spring. At the Jagannath temple, special yellow garments are offered, and the first log of wood for the Rath Yatra chariots is officially sanctified.",
    ritualSchedule: "07:00 AM Saraswati Puja rituals, 10:00 AM Chariot wood log worship",
    visitorGuidelines: "Yellow attire is encouraged for devotees visiting on this day.",
    parkingInformation: "Temple outer ground parking.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_5",
    festivalNameEnglish: "Maha Shivaratri",
    festivalNameOdia: "ମହା ଶିବରାତ୍ରୀ",
    festivalNameHindi: "महा शिवरात्रि",
    date: "2026-02-15",
    startTime: "05:00 AM",
    endTime: "11:50 PM",
    category: "Local Temple Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Special night long lamp offerings at the Shiva shrines within the temple complex.",
    fullDescription: "Although primarily a Jagannath shrine, Maha Shivaratri is celebrated at the Shiva temples situated in the outer wall campus, demonstrating the Harihara union.",
    ritualSchedule: "06:00 AM Rudrabhishek, 10:00 PM Hari-Hara Puja, 11:30 PM Mahadipa lifting",
    visitorGuidelines: "Fasting devotees are requested to wait in designated pandals for Mahadipa.",
    parkingInformation: "High School Bypass ground.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_6",
    festivalNameEnglish: "Dola Purnima",
    festivalNameOdia: "ଦୋଳ ପୂର୍ଣ୍ଣିମା",
    festivalNameHindi: "डोल पूर्णिमा",
    date: "2026-03-03",
    startTime: "05:30 AM",
    endTime: "09:00 PM",
    category: "Major Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Spring festival of colours with deities placed on swing platforms (Dola Bedi).",
    fullDescription: "Celebrated on spring full moon. Dola Govinda (merger form of Krishna-Jagannath) is placed on a beautifully decorated swing platform, and devotees offer Abira (natural color powder).",
    ritualSchedule: "08:00 AM Pahandi to Dola Bedi, 11:00 AM Abira offering, 05:00 PM Rajarajeshwar Besha",
    visitorGuidelines: "Use only dry organic colors (gulal/abir) inside premises. Avoid liquid paint.",
    parkingInformation: "Block Office parking area.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/deity_procession_close.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_7",
    festivalNameEnglish: "Pana Sankranti / Odia New Year",
    festivalNameOdia: "ପଣା ସଂକ୍ରାନ୍ତି / ଓଡ଼ିଆ ନବବର୍ଷ",
    festivalNameHindi: "पना संक्रांति / ओड़िया नववर्ष",
    date: "2026-04-14",
    startTime: "05:00 AM",
    endTime: "08:30 PM",
    category: "Major Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Odia New Year celebrated with distribution of Pana sweet drinks.",
    fullDescription: "Pana Sankranti marks the new solar year in Odisha. A special clay pot with a small hole is hung over the sacred Tulasi plant, and Pana (sweet herbal fruit drink) is offered and distributed to visitors.",
    ritualSchedule: "06:30 AM Hanuman Puja, 10:30 AM Pana offering, 01:00 PM Free Pana distribution counter",
    visitorGuidelines: "Free pana drink cups will be distributed at the main gate.",
    parkingInformation: "Temple ground parking open.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_8",
    festivalNameEnglish: "Akshaya Tritiya",
    festivalNameOdia: "ଅକ୍ଷୟ ତୃତୀୟା",
    festivalNameHindi: "अक्षय तृतीया",
    date: "2026-04-20",
    startTime: "06:00 AM",
    endTime: "08:00 PM",
    category: "Jagannath Ritual",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Commencement of Chariot construction and start of Chandan Yatra.",
    fullDescription: "Akshaya Tritiya is highly sacred. Chariot builders formally start carving the logs (Ratha Anukula). This also marks the beginning of the 21-day water cruise Chandan Yatra.",
    ritualSchedule: "08:00 AM Ratha wood worship, 10:00 AM Chandan paste grinding",
    visitorGuidelines: "Observe the wood carving artisans outside the temple boundary.",
    parkingInformation: "Outer bypass road parking.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_9",
    festivalNameEnglish: "Chandan Yatra",
    festivalNameOdia: "ଶ୍ରୀ ଚନ୍ଦନ ଯାତ୍ରା",
    festivalNameHindi: "चंदन यात्रा",
    date: "2026-04-20",
    startTime: "04:00 PM",
    endTime: "08:30 PM",
    category: "Jagannath Ritual",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "21-day summer cruise of Madan Mohan in the temple pond.",
    fullDescription: "To soothe the Lord during hot summer, Madan Mohan and representatives are smeared with sandalwood paste and taken on beautifully decorated boats (Chapa) in the temple tank.",
    ritualSchedule: "04:30 PM Deity procession to pond, 05:30 PM Water cruise (Chapa Yatra)",
    visitorGuidelines: "Avoid standing on slippery edges of the temple pond. Stay behind barricades.",
    parkingInformation: "Temple pond bypass road.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/jagannath_sanctum_seva.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_10",
    festivalNameEnglish: "Anasara Period",
    festivalNameOdia: "ଅଣସର ସମୟ",
    festivalNameHindi: "अनासर काल",
    date: "2026-06-10",
    startTime: "05:00 AM",
    endTime: "09:00 PM",
    category: "Jagannath Ritual",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "15-day recovery period where deities rest inside the Anasara chamber.",
    fullDescription: "Following the heavy bath of Snana Purnima, Lord Jagannath is believed to fall ill with fever. He rests in the private Anasara chamber for 15 days, where only special herbal treatments (Dasamula) are offered.",
    ritualSchedule: "No public Darshan of deities. Devotees worship Patita Pavan or Alarnath paintings.",
    visitorGuidelines: "Main sanctum is closed. View the Patita Pavan image at the outer courtyard.",
    parkingInformation: "Temple general parking.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/jagannath_sanctum_seva.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_11",
    festivalNameEnglish: "Netrotsava",
    festivalNameOdia: "ନେତ୍ରୋତ୍ସବ",
    festivalNameHindi: "नेत्रोत्सव",
    date: "2026-06-25",
    startTime: "06:00 AM",
    endTime: "09:00 PM",
    category: "Jagannath Ritual",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Re-opening of temple gates after Anasara sickness.",
    fullDescription: "Netrotsava (Festival of the Eyes) is when Lord Jagannath recovers from illness and His eyes are painted anew (Naba Jaubana Darshan) before Rath Yatra.",
    ritualSchedule: "06:00 AM Naba Jaubana Darshan, 10:00 AM Netrotsava Puja offering",
    visitorGuidelines: "Huge rush expected after 15 days of closure. Cooperate with staff.",
    parkingInformation: "High School Ground.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/jagannath_tulasi_closeup.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_12",
    festivalNameEnglish: "Hera Panchami",
    festivalNameOdia: "ହେରା ପଞ୍ଚମୀ",
    festivalNameHindi: "हेरा पंचमी",
    date: "2026-06-30",
    startTime: "05:00 PM",
    endTime: "10:00 PM",
    category: "Jagannath Ritual",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Goddess Laxmi visits Gundicha Temple in anger to retrieve Lord Jagannath.",
    fullDescription: "On the fifth day of Rath Yatra, Goddess Lakshmi goes to Gundicha Temple to find Lord Jagannath, breaking a part of His chariot in anger for not being taken along.",
    ritualSchedule: "06:30 PM Goddess Laxmi procession, 08:30 PM Chariot breaking ritual",
    visitorGuidelines: "Perform offering to Goddess Lakshmi during her procession path.",
    parkingInformation: "Block Office bypass road.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/procession_night_street.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_13",
    festivalNameEnglish: "Bahuda Yatra",
    festivalNameOdia: "ବାହୁଡ଼ା ଯାତ୍ରା",
    festivalNameHindi: "बहुड़ा यात्रा",
    date: "2026-07-04",
    startTime: "06:00 AM",
    endTime: "08:30 PM",
    category: "Major Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "The return procession of the chariots to the main temple.",
    fullDescription: "Bahuda Yatra is the return journey of Lord Jagannath from Gundicha Temple back to the main temple after 9 days.",
    ritualSchedule: "07:00 AM Bahuda Pahandi, 12:00 PM Chariot pulling starts",
    visitorGuidelines: "Do not stand directly in front of the wheels. Stay in queue.",
    parkingInformation: "High School Bypass grounds.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_chariot_sunset.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_14",
    festivalNameEnglish: "Suna Besha",
    festivalNameOdia: "ସୁନା ବେଶ",
    festivalNameHindi: "सुना वेश (स्वर्ण रूप)",
    date: "2026-07-05",
    startTime: "03:00 PM",
    endTime: "11:00 PM",
    category: "Major Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "The deities dressed in solid gold ornaments on their chariots.",
    fullDescription: "Also known as Rajadhiraja Besha, Lord Jagannath is adorned in massive gold crowns, hands, and ornaments directly on the chariot parked in front of the temple.",
    ritualSchedule: "04:00 PM Golden ornaments dressing, 05:00 PM to 10:30 PM Public Darshan",
    visitorGuidelines: "VIP and general queue systems are strictly separated for safety.",
    parkingInformation: "High School Ground and Block Office Bypass.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/jagannath_sanctum_seva.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_15",
    festivalNameEnglish: "Niladri Bije",
    festivalNameOdia: "ନୀଳାଦ୍ରି ବିଜେ",
    festivalNameHindi: "नीलाद्रि बिजे",
    date: "2026-07-07",
    startTime: "04:00 PM",
    endTime: "10:30 PM",
    category: "Jagannath Ritual",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Deities return inside the sanctum. Lord offers Rasagola to Lakshmi.",
    fullDescription: "The return of Lord Jagannath into the inner sanctum (Garbhagriha). Lord Jagannath pacifies Goddess Lakshmi with Rasagola sweet offerings to gain entry after leaving her behind.",
    ritualSchedule: "05:00 PM Rasagola offering ritual, 07:00 PM Pahandi to Ratna Singhasana",
    visitorGuidelines: "Observe the Rasagola festival and purchase fresh offerings at counter.",
    parkingInformation: "Temple general parking.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/deity_procession_close.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_16",
    festivalNameEnglish: "Janmashtami",
    festivalNameOdia: "ଜନ୍ମାଷ୍ଟମୀ",
    festivalNameHindi: "जन्माष्टमी",
    date: "2026-09-04",
    startTime: "06:00 AM",
    endTime: "11:59 PM",
    category: "Special Puja",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "The appearance day of Lord Sri Krishna with midnight rituals.",
    fullDescription: "Celebrated with elaborate midnight rituals, bathing of Baby Krishna (Jeebanyasa), and special sweet offerings.",
    ritualSchedule: "06:30 AM Morning Puja, 10:00 PM Birth rituals, 12:00 AM Midnight Aarti",
    visitorGuidelines: "Late night Darshan allowed. Bring kids for Bal Gopal blessings.",
    parkingInformation: "Temple outer boundary parking.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/jagannath_sanctum_seva.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_17",
    festivalNameEnglish: "Ganesh Chaturthi",
    festivalNameOdia: "ଗଣେଶ ଚତୁର୍ଥୀ",
    festivalNameHindi: "गणेश चतुर्थी",
    date: "2026-09-15",
    startTime: "06:00 AM",
    endTime: "08:30 PM",
    category: "Special Puja",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Worship of Lord Ganesha at the outer temple shrine.",
    fullDescription: "Lord Ganesha is worshiped with modak offerings and special chants at the Ganesh shrine inside the temple complex.",
    ritualSchedule: "08:00 AM Ganesh Puja, 11:30 AM Modak offering, 06:30 PM Sandhya Aarti",
    visitorGuidelines: "Traditional wear requested.",
    parkingInformation: "Temple parking open.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_18",
    festivalNameEnglish: "Nuakhai",
    festivalNameOdia: "ନୂଆଖାଇ",
    festivalNameHindi: "नुआखाई",
    date: "2026-09-16",
    startTime: "06:00 AM",
    endTime: "08:00 PM",
    category: "Community Event",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Agricultural festival of offering the first crop of new rice.",
    fullDescription: "A major harvest festival of Western Odisha, also observed here by offering Nabanna (newly harvested crop cooked with milk and sugar) to the Lord.",
    ritualSchedule: "09:30 AM Nabanna offering to Lord Jagannath, 11:00 AM Prasad consumption",
    visitorGuidelines: "Fasting till Nabanna offering is recommended.",
    parkingInformation: "Temple general parking.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_19",
    festivalNameEnglish: "Durga Puja",
    festivalNameOdia: "ଦୁର୍ଗା ପୂଜା",
    festivalNameHindi: "दुर्गा पूजा",
    date: "2026-10-17",
    startTime: "05:00 AM",
    endTime: "10:30 PM",
    category: "Major Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Vijayadashami celebrations with weapon worship of deities.",
    fullDescription: "Celebrated with Kanak Durga rituals. On Dashami day, Lord Jagannath assumes Rajarajeswar Besha, and traditional weapon worship is performed.",
    ritualSchedule: "06:00 AM Shodasa Upachara Puja, 07:00 PM Vijayadashami Shastra Puja",
    visitorGuidelines: "Avoid carrying large bags. Security checks will be active.",
    parkingInformation: "High School Ground bypass.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_20",
    festivalNameEnglish: "Kumar Purnima",
    festivalNameOdia: "କୁମାର ପୂର୍ଣ୍ଣିମା",
    festivalNameHindi: "कुमार पूर्णिमा",
    date: "2026-10-25",
    startTime: "05:30 AM",
    endTime: "09:00 PM",
    category: "Community Event",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Moon worship and offering of fried paddy to deities.",
    fullDescription: "Celebrated by girls offering prayers to the moon. Lord Jagannath is dressed in clean white garments, and special Khae (fried paddy) is offered.",
    ritualSchedule: "05:00 PM Khae bhoga offering, 06:30 PM Moon-sighting prayers",
    visitorGuidelines: "Evening cultural programs will be held in the temple compound.",
    parkingInformation: "Block Office Ground.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/jagannath_sanctum_seva.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_21",
    festivalNameEnglish: "Kartika Purnima",
    festivalNameOdia: "କାର୍ତ୍ତିକ ପୂର୍ଣ୍ଣିମା",
    festivalNameHindi: "कार्तिक पूर्णिमा",
    date: "2026-11-24",
    startTime: "04:30 AM",
    endTime: "10:00 PM",
    category: "Major Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Boita Bandana ritual and Radha Damodar Vesha of deities.",
    fullDescription: "One of the holiest days. Devotees float paper/cork boats (Boita Bandana) in the temple pond. Lord Jagannath is dressed in the grand Suna Besha (Golden Attire) inside the temple.",
    ritualSchedule: "04:30 AM Boita Bandana, 06:00 AM Suna Besha dressing, 09:30 AM Anna Mahaprasad offering",
    visitorGuidelines: "Float boats only in designated safe pond areas. Strict security in place.",
    parkingInformation: "All parking grounds active with shuttle rickshaws.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/jagannath_sanctum_seva.jpg",
    isFeatured: true,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_22",
    festivalNameEnglish: "Prathamastami",
    festivalNameOdia: "ପ୍ରଥମାଷ୍ଟମୀ",
    festivalNameHindi: "प्रथमाष्टमी",
    date: "2026-12-03",
    startTime: "06:00 AM",
    endTime: "08:30 PM",
    category: "Community Event",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Traditional Odia festival celebrating the first-born child.",
    fullDescription: "The first-born child is showered with blessings. Special Enduri Pitha (rice cakes wrapped in turmeric leaves) is offered to Lord Jagannath.",
    ritualSchedule: "08:00 AM Special puja for first-borns, 11:30 AM Enduri Pitha bhoga offering",
    visitorGuidelines: "Purchase authentic Enduri Pitha at Anandabazar counter.",
    parkingInformation: "Temple parking open.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_23",
    festivalNameEnglish: "Gita Jayanti",
    festivalNameOdia: "ଗୀତା ଜୟନ୍ତୀ",
    festivalNameHindi: "गीता जयंती",
    date: "2026-12-20",
    startTime: "06:00 AM",
    endTime: "08:00 PM",
    category: "Special Puja",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Recitation of Srimad Bhagavad Gita and special homam.",
    fullDescription: "Recitation of Gita chapters and spiritual discourses inside the temple assembly hall.",
    ritualSchedule: "08:30 AM Gita Yajna, 02:00 PM Recitations, 07:00 PM Sandhya Aarti",
    visitorGuidelines: "Join the chanting circle in the assembly hall.",
    parkingInformation: "Temple outer ground.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_24",
    festivalNameEnglish: "Dhanu Sankranti",
    festivalNameOdia: "ଧନୁ ସଂକ୍ରାନ୍ତି",
    festivalNameHindi: "धनु संक्रांति",
    date: "2026-12-16",
    startTime: "05:30 AM",
    endTime: "08:00 PM",
    category: "Special Puja",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Offering of Dhanu Muan sweet to the deities.",
    fullDescription: "Marks the sun's transit into Sagittarius. Special sweet Dhanu Muan (made of puffed rice, jaggery, and ghee) is prepared and offered to the Lord.",
    ritualSchedule: "06:00 AM Dhanu Muan offering rituals, 06:30 PM Sandhya Aarti",
    visitorGuidelines: "Dhanu Muan packets will be available at temple counters.",
    parkingInformation: "Temple parking open.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_25",
    festivalNameEnglish: "Local Temple Annual Festival",
    festivalNameOdia: "ବାର୍ଷିକ ପ୍ରତିଷ୍ଠା ଉତ୍ସବ",
    festivalNameHindi: "स्थानीय मंदिर वार्षिक उत्सव",
    date: "2026-03-15",
    startTime: "05:00 AM",
    endTime: "09:30 PM",
    category: "Local Temple Festival",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Annual establishment anniversary of Sidheswar Temple.",
    fullDescription: "Anniversary of the temple sanctification. 108 pots Abhishek and Yajna are performed in the temple compound.",
    ritualSchedule: "06:00 AM Maha Yajna starts, 12:00 PM Purnahuti, 01:30 PM Annadan for all",
    visitorGuidelines: "Free mass lunch (prasad) will be served to all visiting devotees.",
    parkingInformation: "High School bypass grounds.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/procession_night_street.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_26",
    festivalNameEnglish: "Special Jagannath Puja Days",
    festivalNameOdia: "ଗୁରୁବାର ସ୍ୱତନ୍ତ୍ର ପୂଜା",
    festivalNameHindi: "विशेष गुरुवार पूजा",
    date: "2026-05-14",
    startTime: "06:00 AM",
    endTime: "08:30 PM",
    category: "Special Puja",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Weekly Thursday prayers and Lakshmi rituals.",
    fullDescription: "Every Thursday, special prayers are offered to Goddess Mahalakshmi and Lord Jagannath with yellow flowers.",
    ritualSchedule: "08:00 AM Lakshmi Puja, 06:30 PM Sandhya Deepa offering",
    visitorGuidelines: "Wear traditional clean clothes.",
    parkingInformation: "Temple parking open.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/jagannath_tulasi_closeup.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  },
  {
    id: "fest_27",
    festivalNameEnglish: "Ekadashi / Purnima Observances",
    festivalNameOdia: "ଏକାଦଶୀ ଓ ପୂର୍ଣ୍ଣିମା ନୀତି",
    festivalNameHindi: "एकादशी एवं पूर्णिमा अनुष्ठान",
    date: "2026-07-25",
    startTime: "05:00 AM",
    endTime: "09:30 PM",
    category: "Ekadashi / Purnima / Amavasya",
    status: "Tentative — subject to temple committee confirmation",
    shortDescription: "Monthly Ekadashi Mahadipa and Purnima special offerings.",
    fullDescription: "Observation of holy Ekadashi (raising the Mahadipa on top of temple spire) and Amavasya/Purnima specialized nitis.",
    ritualSchedule: "06:30 PM Ekadashi rituals, 08:30 PM Mahadipa lifting on spire",
    visitorGuidelines: "Watch the temple spire at 08:30 PM to catch sight of the holy light lifting.",
    parkingInformation: "Temple parking open.",
    contactInformation: "+91 93378 22942",
    imageUrl: "/assets/temple_spire_flags.jpg",
    isFeatured: false,
    isPublished: true,
    lastUpdated: "2026-07-04"
  }
];

const SEED_GALLERY = [
  {
    id: "gal_u1",
    title: "Temple Spires with Nilachakra and Flags",
    altText: "Temple Spires with Nilachakra and Flags",
    category: "Temple",
    imageUrl: "/assets/temple_spire_flags.jpg",
    thumbnailUrl: "/assets/temple_spire_flags.jpg",
    caption: "Colourful temple spires crowned with the Nilachakra and fluttering flags against the evening sky.",
    date: "2026-10-02",
    isFeatured: true,
    isApproved: true
  },
  {
    id: "gal_u2",
    title: "Lord Jagannath Procession at Night",
    altText: "Lord Jagannath Procession at Night",
    category: "Festivals",
    imageUrl: "/assets/deity_procession_close.jpg",
    thumbnailUrl: "/assets/deity_procession_close.jpg",
    caption: "Lord Jagannath adorned with Tulasi and flowers, carried in procession among devotees with decorated chhatras.",
    date: "2026-10-02",
    isFeatured: true,
    isApproved: true
  },
  {
    id: "gal_u3",
    title: "Hanuman Shrine",
    altText: "Hanuman Shrine",
    category: "Deities",
    imageUrl: "/assets/hanuman_shrine.jpg",
    thumbnailUrl: "/assets/hanuman_shrine.jpg",
    caption: "Hanuman idol with folded hands, offered fresh flowers inside the temple premises.",
    date: "2026-10-02",
    isFeatured: true,
    isApproved: true
  },
  {
    id: "gal_u4",
    title: "Devotees Gathered for the Night Procession",
    altText: "Devotees Gathered for the Night Procession",
    category: "Festivals",
    imageUrl: "/assets/procession_night_street.jpg",
    thumbnailUrl: "/assets/procession_night_street.jpg",
    caption: "A large gathering of devotees lining the street, with the deity procession and festive lights above.",
    date: "2026-10-02",
    isFeatured: true,
    isApproved: true
  },
  {
    id: "gal_u5",
    title: "Temple and Chariot at Sunset",
    altText: "Temple and Chariot at Sunset",
    category: "Rath Yatra",
    imageUrl: "/assets/temple_chariot_sunset.jpg",
    thumbnailUrl: "/assets/temple_chariot_sunset.jpg",
    caption: "The colourful chariot and temple complex glowing under a golden sunset sky.",
    date: "2026-10-02",
    isFeatured: true,
    isApproved: true
  },
  {
    id: "gal_u6",
    title: "Lord Jagannath Adorned with Tulasi Garlands",
    altText: "Lord Jagannath Adorned with Tulasi Garlands",
    category: "Deities",
    imageUrl: "/assets/jagannath_sanctum_seva.jpg",
    thumbnailUrl: "/assets/jagannath_sanctum_seva.jpg",
    caption: "Lord Jagannath in the sanctum, decorated with Tulasi leaves and marigold garlands, with flower offerings in front.",
    date: "2026-10-02",
    isFeatured: true,
    isApproved: true
  },
  {
    id: "gal_u7",
    title: "Lord Jagannath - Divine Darshan",
    altText: "Lord Jagannath - Divine Darshan",
    category: "Deities",
    imageUrl: "/assets/jagannath_tulasi_closeup.jpg",
    thumbnailUrl: "/assets/jagannath_tulasi_closeup.jpg",
    caption: "A close view of the Lord's large eyes, framed by Tulasi leaves, marigolds and jasmine flowers.",
    date: "2026-10-02",
    isFeatured: true,
    isApproved: true
  },
];

const SEED_FAQS = [
  {
    id: "faq_1",
    questionEn: "What are the timings of Mangala Aarti?",
    questionOr: "ମଙ୍ଗଳ ଆଳତି ର ସମୟ କେତେବେଳେ?",
    questionHi: "मंगला आरती का समय कब है?",
    answerEn: "Mangala Aarti takes place daily at 05:30 AM right after the temple gates open at 05:00 AM.",
    answerOr: "ମନ୍ଦିର ଦ୍ଵାର ସକାଳ ୫:୦୦ ରେ ଖୋଲିବା ପରେ ମଙ୍ଗଳ ଆଳତି ଦୈନିକ ସକାଳ ୫:୩୦ ରେ ହୋଇଥାଏ।",
    answerHi: "मंदिर के द्वार सुबह 05:00 बजे खुलने के तुरंत बाद मंगला आरती दैनिक रूप से सुबह 05:30 बजे होती है।"
  },
  {
    id: "faq_2",
    questionEn: "Are mobile phones allowed inside the temple premises?",
    questionOr: "ମନ୍ଦିର ପରିସର ମଧ୍ୟକୁ ମୋବାଇଲ୍ ଫୋନ ନେବା ଅନୁମତି ଅଛି କି?",
    questionHi: "क्या मंदिर परिसर के भीतर मोबाइल फोन ले जाने की अनुमति है?",
    answerEn: "Mobile phones and photography are strictly prohibited inside the main temple premises. Devotees are requested to keep their phones at the Temple Office shoe-counter locker.",
    answerOr: "ମୁଖ୍ୟ ମନ୍ଦିର ପରିସର ମଧ୍ୟରେ ମୋବାଇଲ୍ ଫୋନ ବ୍ୟବହାର ଏବଂ ଫଟୋଗ୍ରାଫି ସମ୍ପୂର୍ଣ୍ଣ ନିଷେଧ। ଶ୍ରଦ୍ଧାଳୁମାନଙ୍କୁ ସେମାନଙ୍କ ଫୋନ ମନ୍ଦିର କାର୍ଯ୍ୟାଳୟ ର ଜୋତା କାଉଣ୍ଟର ଲକରରେ ରଖିବାକୁ ଅନୁରୋଧ।",
    answerHi: "मुख्य मंदिर परिसर के भीतर मोबाइल फोन और फोटोग्राफी सख्त वर्जित हैं। श्रद्धालुओं से अनुरोध है कि वे अपने फोन मंदिर कार्यालय के जूता काउंटर लॉकर में रखें।"
  }
];

export { SEED_NOTICES, SEED_FESTIVALS, SEED_GALLERY, SEED_FAQS };
